// react/src/components/threeViewer.tsx
import * as React from 'react';

import { ThreeViewerBase } from '@panorama-viewer/client';

export default class ThreeViewer extends React.Component<any, {}> {
    private base: ThreeViewerBase = new ThreeViewerBase();
    private host: any;

    componentDidMount() {
        this.base.item = this.props.item;
        const canvas = this.host;
        this.base.init(canvas);
        canvas.addEventListener('mousedown', e => this.base.onMouseDown(e));
        canvas.addEventListener('mousemove', e => this.base.onMouseMove(e));
        canvas.addEventListener('mouseup', e => this.base.onMouseUp());
        canvas.addEventListener('mousewheel', e => this.base.onMouseWheel(e));
        canvas.addEventListener('keyup', e => this.base.onKeyUp(e));
        window.addEventListener('resize', e => this.base.onResize(canvas));
    }

    componentWillReceiveProps(props) {
        if (this.props.item !== props.item) {
            this.base.item = props.item;
        }
    }

    render() {
        return (<div style={{ cursor: 'move' }} ref={host => this.host = host} />);
    }
}

// angular/src/app/components/threeViewer.ts
import { Component, Input, AfterViewInit, ElementRef, HostListener } from '@angular/core';

import { Panorama } from '@panorama-viewer/model';
import { ThreeViewerBase } from '@panorama-viewer/client';

@Component({
    selector: 'threeViewer',
    template: '',
    styles: [':host { cursor: move; }']
})
export class ThreeViewer extends ThreeViewerBase implements AfterViewInit {
    @Input()
    set item(value: Panorama) {
        super.item = value;
    }

    constructor(private host: ElementRef) {
        super();
    }

    ngAfterViewInit() {
        super.init(this.host.nativeElement);
    }

    @HostListener('window:resize', ['$event'])
    onResize($event: any) {
        super.onResize(this.host.nativeElement);
    }

    @HostListener('mousedown', ['$event'])
    onMouseDown($event: any) {
        super.onMouseDown($event);
    }

    @HostListener('mousemove', ['$event'])
    onMouseMove($event: any) {
        super.onMouseMove($event);
    }

    @HostListener('mouseup', ['$event'])
    onMouseUp() {
        super.onMouseUp();
    }

    @HostListener('mousewheel', ['$event'])
    onMouseWheel($event: any) {
        super.onMouseWheel($event);
    }

    @HostListener('keyup', ['$event'])
    onKeyUp($event: any) {
        super.onKeyUp($event);
    }
}
